# ==============================
# templates/00-namespace.yaml
# ==============================
{{- if .Values.manageNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "kafka.ns" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1000"
    "helm.sh/resource-policy": keep
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "kafka-ui.ns" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1000"
    "helm.sh/resource-policy": keep
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "schema-registry.ns" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1000"
    "helm.sh/resource-policy": keep
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "lag-exporter.ns" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1000"
    "helm.sh/resource-policy": keep
{{- end }}
