{{- $ns := include "kafka.ns" . -}}
{{- if and .Values.azure.keyVaultName .Values.tls.materialize.enabled }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ default "kafka-akv-secrets-spc" .Values.tls.spcName }}
  namespace: {{ $ns }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.azure.uamiClientId | quote }}
    keyvaultName: {{ .Values.azure.keyVaultName | quote }}
    tenantId: {{ .Values.azure.tenantId | quote }}
    objects: |
      array:
        # TLS bundle for external listener (PEM with key + fullchain)
        - |
          objectName: {{ default "kafka-tls" .Values.tls.certObjectName }}
          objectType: secret
          objectAlias: tls.crtkey.pem

        # OIDC: audience appId + tenant (required for JAAS construction)
        {{- with .Values.oauthAkvAudienceObjectName }}
        - |
          objectName: {{ . }}
          objectType: secret
          objectAlias: kafka-oidc-audience
        {{- end }}
        {{- with .Values.oauthAkvTenantObjectName }}
        - |
          objectName: {{ . }}
          objectType: secret
          objectAlias: kafka-oidc-tenant
        {{- end }}

        # Kafka-UI (confidential client)
        - |
          objectName: {{ .Values.kafkaUi.sso.clientIdAkvName | quote }}
          objectType: secret
          objectAlias: kafka-ui-client-id
        - |
          objectName: {{ .Values.kafkaUi.sso.clientSecretAkvName | quote }}
          objectType: secret
          objectAlias: kafka-ui-client-secret

        # Kafka Exporter dedicated client
        - |
          objectName: kafka-lag-client-id-{{ .Values.env | default "dev1" }}
          objectType: secret
          objectAlias: kafka-lag-client-id
        - |
          objectName: kafka-lag-client-secret-{{ .Values.env | default "dev1" }}
          objectType: secret
          objectAlias: kafka-lag-client-secret

        # Schema Registry dedicated client
        - |
          objectName: kafka-schema-client-id-{{ .Values.env | default "dev1" }}
          objectType: secret
          objectAlias: kafka-schema-client-id
        - |
          objectName: kafka-schema-client-secret-{{ .Values.env | default "dev1" }}
          objectType: secret
          objectAlias: kafka-schema-client-secret
{{- end }}
