# ==============================
# templates/40-kafka-ui-configmap.yaml
# ==============================
{{- if .Values.kafkaUi.enabled }}
{{- $kui   := .Values.kafkaUi | default (dict) -}}
{{- $kuiTls := $kui.tls | default (dict) -}}
{{- $names := $kui.names | default (dict) -}}
{{- $nsK   := include "kafka.ns" . -}}
{{- $nsUI  := include "kafka-ui.ns" . -}}
{{- $nsSR  := include "schema-registry.ns" . | default "schema-registry" -}}
{{- $name  := include "kafka.name" . -}}
{{- $defaultBootstrap := printf "%s-kafka-bootstrap.%s.svc.cluster.local:9092" $name $nsK -}}
{{- $ver   := default "v2" $kui.oauth.issuerVersion -}}
{{- $token := include "kafka.tokenEndpoint" (dict "ver" $ver "ctx" .) | trim -}}
{{- $ext   := $kui.externalCluster | default (dict) -}}
{{- $extEnabled := and ($ext.enabled | default false) ($ext.bootstrapServers | default "") -}}
{{- $extBootstrap := default "" $ext.bootstrapServers -}}
{{- $extName := default "external" $ext.name -}}
{{- $extProtocol := default "SASL_SSL" $ext.securityProtocol -}}
{{- $extOauth := $ext.oauth | default (dict) -}}
{{- $extReuse := default true $extOauth.reusePrimarySecret -}}
{{- $extSchema := $ext.schemaRegistryUrl | default ($kui.schemaRegistryUrl | default (printf "http://schema-registry-port.%s.svc.cluster.local:8081" $nsSR)) -}}
{{- $extVer := default $ver $ext.oauth.issuerVersion -}}
{{- $tokenExt := include "kafka.tokenEndpoint" (dict "ver" $extVer "ctx" .) | trim -}}
{{- $extTls := $ext.tls | default (dict) -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui
  namespace: {{ $nsUI }}
  labels: { app: kafka-ui }
data:
  KAFKA_CLUSTERS_0_NAME: {{ (get $names "internal" | default "internal") | quote }}
  KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: {{ $defaultBootstrap | quote }}
  KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: {{ default "SASL_SSL" $kui.oauth.securityProtocol | quote }}
  KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: "OAUTHBEARER"
  KAFKA_CLUSTERS_0_PROPERTIES_SASL_LOGIN_CALLBACK_HANDLER_CLASS: "org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerLoginCallbackHandler"
  KAFKA_CLUSTERS_0_PROPERTIES_SASL_OAUTHBEARER_TOKEN_ENDPOINT_URL: {{ $token | quote }}
{{- if $kuiTls.caSecretName }}
  KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_TYPE: "PEM"
  KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: {{ printf "%s/%s" (default "/etc/kafka/cluster-ca" $kuiTls.mountPath) (default "ca.crt" $kuiTls.caCertificate) | quote }}
{{- end }}
  KAFKA_CLUSTERS_0_SCHEMAREGISTRY: {{ ($kui.schemaRegistryUrl | default (printf "http://schema-registry-port.%s.svc.cluster.local:8081" $nsSR)) | quote }}
  AUTH_TYPE: {{ ($kui.auth.type | default "DISABLED") | quote }}
  DYNAMIC_CONFIG_ENABLED: "true"
{{- if $extEnabled }}
  KAFKA_CLUSTERS_1_NAME: {{ (get $names "external" | default $extName) | quote }}
  KAFKA_CLUSTERS_1_BOOTSTRAP_SERVERS: {{ $extBootstrap | quote }}
  KAFKA_CLUSTERS_1_PROPERTIES_SECURITY_PROTOCOL: {{ $extProtocol | quote }}
  KAFKA_CLUSTERS_1_PROPERTIES_SASL_MECHANISM: "OAUTHBEARER"
  KAFKA_CLUSTERS_1_PROPERTIES_SASL_LOGIN_CALLBACK_HANDLER_CLASS: "org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerLoginCallbackHandler"
  KAFKA_CLUSTERS_1_PROPERTIES_SASL_OAUTHBEARER_TOKEN_ENDPOINT_URL: {{ $tokenExt | quote }}
{{- if $extTls.caSecretName }}
  KAFKA_CLUSTERS_1_PROPERTIES_SSL_TRUSTSTORE_TYPE: "PEM"
  KAFKA_CLUSTERS_1_PROPERTIES_SSL_TRUSTSTORE_LOCATION: {{ printf "%s/%s" (default "/etc/kafka/external-ca" $extTls.mountPath) (default "ca.crt" $extTls.caCertificate) | quote }}
{{- end }}
  KAFKA_CLUSTERS_1_SCHEMAREGISTRY: {{ $extSchema | quote }}
{{- end }}
{{- end }}
