# ================================
# Env selector
# ================================
env: "prod"
dns:
  subdomain: "nprod"
  domain: "az.vzp.cz"
# ================================
# Namespaces
# ================================
namespaces:
  kafka: kafka
  kafkaUi: kafka-ui
  schemaRegistry: schema-registry

# ================================
# Azure
# ================================
azure:
  keyVaultName: "kv-vzp-prod-we-aks-002"
  uamiClientId: ""  # CHANGE IT

oauthAkvAudienceObjectName: ""
oauthAkvTenantObjectName: ""

# ================================
# KafkaUser principals
# ================================
kafkaUsers:
  enabled: true
  ui:
    principal: ""
  lag:
    principal: ""
  schema:
    principal: ""

# ================================
# Kafka cluster
# ================================
kafka:
  name: "kafka-vzp-prod-we-002"
  oauth:
    audienceAppId: ""
  authorization:
    type: simple
    superUsers:
      - "CN=kafka-vzp-prod-we-002-entity-operator"
  nodePools:
    - name: broker
      replicas: 3
      roles: [broker, controller]
      storage:
        type: jbod
        volumes:
          - id: 0
            type: persistent-claim
            size: 20Gi
            class: managed-csi
            kraftMetadata: shared
            deleteClaim: false
  config:
    default.replication.factor: 3
    offsets.topic.replication.factor: 3
    transaction.state.log.replication.factor: 3
    min.insync.replicas: 2
    transaction.state.log.min.isr: 2
  listeners:
    internal:
      issuerVersion: v2
      port: 9092
      tls: true
    external:
      port: 9094
      tls: true
      issuerVersion: v2
      bootstrap:
        loadBalancerIP: ""
      brokers:
        - id: 0
          advertisedHost: kafka-0.nprod.az.vzp.cz
          loadBalancerIP: ""
        - id: 1
          advertisedHost: kafka-1.nprod.az.vzp.cz
          loadBalancerIP: ""
        - id: 2
          advertisedHost: kafka-2.nprod.az.vzp.cz
          loadBalancerIP: ""

# ================================
# Kafka-UI
# ================================
kafkaUi:
  names:
    internal: "in-cluster"
    external: "aks-external"
  ingress: { enabled: false }
  service:
    type: LoadBalancer
    port: 80
    annotations: {}
  sso:
    clientIdAkvName: ""
    clientSecretAkvName: ""
  oauth:
    issuerVersion: v2
    securityProtocol: "SASL_SSL"
    k8sSecretName: kafka-ui-oauth
    jaasKey: "sasl-jaas-config"
  tls:
    caSecretName: ""
    caCertificate: ca.crt
    mountPath: /etc/kafka/cluster-ca
  externalCluster:
    enabled: true
    name: "aks-external"
    bootstrapServers: "kafka.nprod.az.vzp.cz:9094"
    securityProtocol: "SASL_SSL"
    schemaRegistryUrl: ""
    tls:
      caSecretName: "kafka-external-ca"
      caCertificate: ca.crt
      mountPath: /etc/kafka/external-ca
    oauth: {}
  schemaRegistryUrl: "http://schema-registry.nprod.az.vzp.cz:8081"
  auth: { type: OAUTH2 }
  domain: ""

# ================================
# Schema Registry
# ================================
schemaRegistry:
  enabled: true
  image: "confluentinc/cp-schema-registry:7.9.0"
  replicas: 1
  service:
    type: ClusterIP
    port: 8081
  kafkaBootstrap: "kafka-vzp-prod-we-002-kafka-bootstrap.kafka.svc.cluster.local:9092"
  compatibilityLevel: "BACKWARD"
  kafkastoreReplicationFactor: 3
  securityProtocol: "SASL_SSL"
  oauth:
    issuerVersion: v2
    k8sSecretName: schema-registry-oauth
    jaasKey: sasl-jaas-config
  tls:
    caSecretName: ""
    caCertificate: ca.crt
    mountPath: /etc/kafka/cluster-ca

# ================================
# Kafka Lag Exporter
# ================================
kafkaExporter:
  enabled: true
  securityProtocol: "SASL_SSL"
  oauth:
    k8sSecretName: kafka-lag-exporter-oauth
    jaasKey: sasl-jaas-config
  tls:
    caSecretName: ""
    caCertificate: ca.crt
    mountPath: /etc/kafka/cluster-ca

# ================================
topics: []
